# Permalinks
permalink:      /:year/:month/:day/:title/

# Setup
title:          temporalcohesion.co.uk
paginate:       5
baseurl:        ""
url:            "http://temporalcohesion.co.uk"
rss_path:       feed.xml

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown
disqus:         temporalcohesion
google_analytics: UA-9870754-1

# About
author:
  name:         Stuart Grassie 
  url:          http://chester.how
  email:        sgrassie@gmail.com
  github:       sgrassie
  twitter:      stugrassie
  linkedin:     sgrassie
  bio:          A software developer in the North of England.
  email_md5:    77b10422593a1c0b9b170f4513fb0c0c

# Custom vars
version:        1.3.0
github:
  repo:         https://github.com/sgrassie/sgrassie.github.io

# Gems
gems:
  - jekyll-paginate
