# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

permalink: date
paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
excerpt_separator: ""
exclude: ["README.md"] # files to exclude
highlighter: pygments
markdown: kramdown
disqus: temporalcohesion
google_analytics: UA-9870754-1

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: temporalcohesion.co.uk

description: Stylish Jekyll Theme
author:
  name: Stuart Grassie
  email: sgrassie@gmail.com
  github: sgrassie
  twitter: stugrassie
  linkedin: sgrassie
  bio: I write software for cash
  email_md5: 77b10422593a1c0b9b170f4513fb0c0c

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

# set it as url of an image
# sidebar_background_image: https://www.dropbox.com/s/g9h23zrycedxtk5/sky.png?raw=1

BASE_PATH:

gems:
  - jekyll-paginate
